server:
  port: 8081

spring:
  h2:
    console:
      path: /h2-ui
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope:
        - read
        - write